# Generated by Django 3.1.3 on 2020-11-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidapp',
            name='author',
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='date_analysed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
