# Generated by Django 3.1.3 on 2020-11-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_androidapp_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='VT_Link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_msg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_positive_engines',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_resource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_responseCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_scanId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='VT_total_engines',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='privacy_policy_classification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='privacy_policy_language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='privacy_policy_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='privacy_policy_text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
