# Generated by Django 3.1.3 on 2020-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0007_auto_20201124_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='download_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
