# Generated by Django 3.1.3 on 2020-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0008_androidapp_download_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='decompile_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
