# Generated by Django 3.1.3 on 2020-11-24 06:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0010_androidapp_xapk'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='PermissionsProtectionLevelList',
            field=django_mysql.models.ListCharField(models.CharField(max_length=99), blank=True, max_length=5000, null=True, size=50),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='ThirdPartyLibraryCategoryList',
            field=django_mysql.models.ListCharField(models.CharField(max_length=99), blank=True, max_length=5000, null=True, size=50),
        ),
    ]
