# Generated by Django 3.1.3 on 2020-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0011_auto_20201124_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='meta_info_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
