# Generated by Django 3.1.3 on 2020-11-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0012_auto_20201124_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='meta_info_developer_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
