# Generated by Django 3.1.3 on 2020-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0013_androidapp_meta_info_developer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='privacy_policy_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
